# Generated by Django 4.1.4 on 2022-12-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee_id',
            field=models.IntegerField(default=0, verbose_name='Emp.Id:'),
        ),
    ]
