# Generated by Django 4.1.4 on 2022-12-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leave_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('n/a', 'N/A'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='N/A', max_length=30, verbose_name='Leave Status'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('n/a', 'N/A'), ('casual_leave', 'Casual Leave'), ('sick_leave', 'Sick Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'Paternity Leave'), ('loss_of_pay_leave', 'Loss of Pay Leave'), ('bereavement_leave', 'Bereavement Leave')], default='N/A', max_length=50, verbose_name='Leave Type'),
        ),
    ]
