# Generated by Django 4.1.4 on 2022-12-12 07:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leave_leave_status_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='applied_to',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('saravana_kumar', 'Saravana Kumar'), ('rajeshwari', 'Rajeshwari'), ('viswanath', 'Viswanath'), ('shiva_ganesh', 'Shiva Ganesh'), ('anshu_kumar', 'Anshu Kumar'), ('aishwarya', 'Aishwarya')], default='N/A', max_length=50, verbose_name='Applied To'),
        ),
    ]
