# Generated by Django 4.1.4 on 2022-12-12 08:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leave_applied_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='description',
            field=models.CharField(db_index=True, default='Description & Responsibilities Assigned', max_length=400, verbose_name='Description & Responsibilities Assigned'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='applied_to',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('saravana_kumar', 'Saravana Kumar'), ('rajeshwari', 'Rajeshwari'), ('viswanath', 'Viswanath'), ('shiva_ganesh', 'Shiva Ganesh'), ('anshu_kumar', 'Anshu Kumar'), ('aishwarya', 'Aishwarya'), ('sajid', 'Sajid'), ('prasanna', 'Prasanna'), ('jithin', 'Jithin')], default='N/A', max_length=500, verbose_name='Applied To'),
        ),
    ]
