# Generated by Django 4.1.4 on 2022-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_leave_description_alter_leave_applied_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='description',
            field=models.CharField(db_index=True, default='Description & Responsibilities Assigned', max_length=400, verbose_name='Notes'),
        ),
    ]
