# Generated by Django 4.1.4 on 2022-12-12 08:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_alter_leave_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='applied_to',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('saravana_kumar', 'Saravana Kumar'), ('rajeshwari', 'Rajeshwari'), ('viswanath', 'Viswanath'), ('shiva_ganesh', 'Shiva Ganesh'), ('anshu_kumar', 'Anshu Kumar'), ('aishwarya', 'Aishwarya Shetty'), ('sajid', 'Sajid Khurshid'), ('prasanna', 'Prasanna Akash'), ('jithin', 'Jithin Peter'), ('nitesh', 'Nitesh Tiwari')], default='saravana_kumar', max_length=500, verbose_name='Applied To'),
        ),
    ]
